[theme]
primaryColor="#4ade80"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#ffffff"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true

